### ISSUE TITLE
Peer Review 2011 / 2010 / 2009

### ISSUE THREAD

**Issue by colecornford** [cmlh/Top-25#3]
Hi Christian,

Saintization for CWE-78 is mispelled.

2011 is fine.

2010 has a few errors which stem from making a duplicate #14. These are listed here.

- CWE-98 > is 14, should be 13
- CWE-129 > is 15, should be 14
- CWE-754 > is 13, should be 15
- CWE-190 > is 17, should be 16
- CWE-209 > is 16, should be 17

2009 is a bit messy to review but that's not your fault, they didn't have an order back in the day. Anyway, 2009 seems fine to me as all the items listed are mapped.

Cole

**Comment by cmlh** [comment]
Fix #3

https://github.com/cmlh/Top-25/releases/tag/alpha.3

Thanks @colecornford
